### PR TITLE
Db.doc updates

### PR DESCRIPTION
**Pull request by dbarbato-sf**

### CODE REVIEW

**Comment by monkey-jeff** [comment]
Just as a note...do we want to change the package "website" to point to the docs page once it is up?

**Comment by dbarbato-sf** [comment]
> Just as a note...do we want to change the package "website" to point to the docs page once it is up?

What do you mean by package website?

**Comment by wjhsf** [comment]
> > Just as a note...do we want to change the package "website" to point to the docs page once it is up?
> 
> What do you mean by package website?

https://github.com/SalesforceCommerceCloud/commerce-sdk/blob/0fc7a682ca979d4d06d5546e3da69c82c4648f11/packages/generator/package.json#L5

"homepage" in the package.json, primarily used by npmjs.com to link to projects.

image

**Comment by dbarbato-sf** [comment]
Ahh I see. I don't know if I'd have a preference to this pointing to CCDC and it having a reference to our SDK doc. Thoughts?

**Pull request merged**
